export const products = [
  {
    _id: "618fa8aef5239e0734f389b3",
    name: "کفش برند Winter body",
    description: [
      { support: "گارانتی مادام العمر" },
      { support: "ارسال رایگان" },
      { support: "اورجینال" },
    ],
    price: 120,
    discount: 0,
    offPrice: 120,
    image: "https://s4.uupload.ir/files/item1_soj.jpg",
  },
  {
    _id: "618fa8aef5239e0734f389b7",
    name: "کفش برند آدیداس",
    description: [{ support: "گارانتی مادام العمر" }, { support: "اورجینال" }],
    price: 110,
    discount: 8,
    offPrice: 100,
    image: "https://s4.uupload.ir/files/item2_fc5s.jpg",
  },
  {
    _id: "618fa8aef5239e0734f389ba",
    name: "کفش برند Vans",
    description: [
      { support: "گارانتی مادام العمر" },
      { support: "اورجینال" },
      { support: "ارسال رایگان" },
    ],
    price: 99,
    discount: 10,
    offPrice: 89,
    image: "https://s4.uupload.ir/files/item3_zvc9.jpg",
  },
  {
    _id: "618fa8aef5239e0734f389be",
    name: "کفش اسپورت",
    description: [
      { support: "گارانتی مادام العمر" },
      { support: "اورجینال" },
      { support: "ارسال رایگان" },
    ],
    price: 260,
    discount: 15,
    offPrice: 220,
    image: "https://s4.uupload.ir/files/item4_zr94.jpg",
  },
  {
    _id: "618fa8aef5239e0734f389c2",
    name: "کفش کراپ",
    description: [
      { support: "گارانتی مادام العمر" },
      { support: "اورجینال" },
      { support: "ارسال رایگان" },
    ],
    price: 150,
    discount: 0,
    offPrice: 150,
    image: "https://s4.uupload.ir/files/item5_24ye.jpg",
  },
  {
    _id: "618fa8aef5239e0734f389c6",
    name: "کفش آبی ساده",
    description: [
      { support: "گارانتی مادام العمر" },
      { support: "اورجینال" },
      { support: "ارسال رایگان" },
    ],
    price: 220,
    discount: 13,
    offPrice: 200,
    image: "https://s4.uupload.ir/files/item6_7jfy.jpg",
  },
];
